# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.5, generator: @autorest/python@6.4.11)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

from azure.core import CaseInsensitiveEnumMeta


class ChatCompletionMessageRole(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Role."""

    ASSISTANT = "assistant"
    USER = "user"
    SYSTEM = "system"


class ChatCompletionObject(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Object."""

    CHAT_COMPLETION = "chat.completion"


class ChatCompletionRequestMessageRole(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The role of the message."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class CompletionObject(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Object."""

    TEXT_COMPLETION = "text_completion"


class EmbeddingObject(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Object."""

    LIST = "list"


class ModelDataObject(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Object."""

    MODEL = "model"


class ModelListObject(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Object."""

    LIST = "list"
